name: TESTING - Build and Deploy to GCR engaged-beaker-303818
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
env:
  PROJECT_ID: engaged-beaker-303818
  IMAGE: wshop
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        export_default_credentials: true


    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker
        
        
    - run: |-
       cp entrypoints/testing.sh start.sh && \
       cp .env.sample .env
        
    
    - name: Replace values in environment file
      uses: vafinvr/template-env-action@master
      env:
        # PG SERVER CONFIG
        P_NODEENV: development
        # API PORT
        P_PORT: 8080

      with:
        filename: .env


    # Build the Docker image
    - name: Build image
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
    # Push the Docker image to Google Container Registry
    - name: Publish image
      run: |-
        gcloud docker -- push gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
    # docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        gcloud run deploy ${{ env.IMAGE }} \
        --image gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:"$GITHUB_SHA" \
        --region us-east1 \
        --platform managed \
        --allow-unauthenticated
